---
kind: "operation"
client: "rug-cli 0.23.0-SNAPSHOT"
generator:
  name: "NewRugArchiveProject"
  group: "atomist-rugs"
  artifact: "rug-archive"
  version: "0.11.0"
  origin:
    repo: "https://github.com/atomist-rugs/rug-archive.git"
    branch: "a881183f4382aa17443b589213889902d2ae69ac"
    sha: "a881183"
  parameters:
    - "editor_name": "ChangeMainToPrint"
    - "project_name": "elm-katz-rugs"

---
kind: "operation"
client: "rug-cli 0.23.0-SNAPSHOT"
editor:
  name: "atomist-rugs.rug-editors.AddTypeScriptEditor"
  group: "atomist-rugs"
  artifact: "rug-editors"
  version: "0.8.0"
  origin:
    repo: "https://github.com/atomist-rugs/rug-editors.git"
    branch: "b29e16a2eb08430790d6ef7d72ab2c199786d7c0"
    sha: "b29e16a"
  parameters:
    - "editor_name": "Hello"

---
kind: "operation"
client: "rug-cli 0.23.1-SNAPSHOT"
editor:
  name: "atomist-rugs.rug-editors.AddTypeScriptEditor"
  group: "atomist-rugs"
  artifact: "rug-editors"
  version: "0.8.0"
  origin:
    repo: "https://github.com/atomist-rugs/rug-editors.git"
    branch: "b29e16a2eb08430790d6ef7d72ab2c199786d7c0"
    sha: "b29e16a"
  parameters:
    - "editor_name": "UpgradeToBeginnerProgram"

---
kind: "operation"
client: "rug-cli 0.23.0"
editor:
  name: "atomist-rugs.rug-editors.AddTypeScriptEditor"
  group: "atomist-rugs"
  artifact: "rug-editors"
  version: "0.8.0"
  origin:
    repo: "https://github.com/atomist-rugs/rug-editors.git"
    branch: "b29e16a2eb08430790d6ef7d72ab2c199786d7c0"
    sha: "b29e16a"
  parameters:
    - "editor_name": "UpgradeToBeginnerProgram"

